// components/tools/QuestionPanel/constants/themes.js
import { FaSun, FaMoon, FaCode } from 'react-icons/fa';

export const themes = {
  light: {
    name: 'Light',
    icon: FaSun,
    bg: 'bg-white',
    bgSecondary: 'bg-gray-50',
    bgTertiary: 'bg-gray-100',
    bgHeader: 'bg-white',
    text: 'text-gray-900',
    textSecondary: 'text-gray-600',
    textMuted: 'text-gray-400',
    border: 'border-gray-200',
    borderHover: 'hover:border-gray-300',
    cardBg: 'bg-white',
    codeBg: 'bg-gray-50',
    consoleBg: 'bg-white',
    consoleText: 'text-gray-900',
    buttonBg: 'bg-white',
    buttonHover: 'hover:bg-gray-50',
    buttonActiveBg: 'bg-gray-100',
    accentBg: 'bg-blue-50',
    accentText: 'text-blue-600',
    accentBorder: 'border-blue-500',
    successBg: 'bg-green-50',
    successText: 'text-green-600',
    warningBg: 'bg-yellow-50',
    warningText: 'text-yellow-600',
    dangerBg: 'bg-red-50',
    dangerText: 'text-red-600',
    editorTheme: 'vs-light',
    shadow: 'shadow-sm',
    tabActive: 'border-b-2 border-blue-500 text-blue-600',
    tabInactive: 'text-gray-500 hover:text-gray-700',
    inputBg: 'bg-white',
    inputBorder: 'border-gray-300',
    inputFocus: 'focus:ring-blue-500 focus:border-blue-500',
    outputBg: 'bg-white',
    outputText: 'text-gray-800',
    outputBorder: 'border-gray-200',
  },
  dark: {
    name: 'Dark',
    icon: FaMoon,
    bg: 'bg-[#1e1e1e]',
    bgSecondary: 'bg-[#252526]',
    bgTertiary: 'bg-[#2d2d2d]',
    bgHeader: 'bg-[#252526]',
    text: 'text-gray-100',
    textSecondary: 'text-gray-300',
    textMuted: 'text-gray-500',
    border: 'border-[#3e3e3e]',
    borderHover: 'hover:border-[#4e4e4e]',
    cardBg: 'bg-[#252526]',
    codeBg: 'bg-[#1e1e1e]',
    consoleBg: 'bg-[#1e1e1e]',
    consoleText: 'text-gray-100',
    buttonBg: 'bg-[#2d2d2d]',
    buttonHover: 'hover:bg-[#3e3e3e]',
    buttonActiveBg: 'bg-[#3e3e3e]',
    accentBg: 'bg-blue-900/30',
    accentText: 'text-blue-400',
    accentBorder: 'border-blue-400',
    successBg: 'bg-green-900/30',
    successText: 'text-green-400',
    warningBg: 'bg-yellow-900/30',
    warningText: 'text-yellow-400',
    dangerBg: 'bg-red-900/30',
    dangerText: 'text-red-400',
    editorTheme: 'vs-dark',
    shadow: 'shadow-lg shadow-black/20',
    tabActive: 'border-b-2 border-blue-400 text-blue-400',
    tabInactive: 'text-gray-400 hover:text-gray-200',
    inputBg: 'bg-[#3e3e3e]',
    inputBorder: 'border-[#4e4e4e]',
    inputFocus: 'focus:ring-blue-400 focus:border-blue-400',
    outputBg: 'bg-[#252526]',
    outputText: 'text-gray-200',
    outputBorder: 'border-[#3e3e3e]',
  },
  github: {
    name: 'GitHub',
    icon: FaCode,
    bg: 'bg-[#0d1117]',
    bgSecondary: 'bg-[#161b22]',
    bgTertiary: 'bg-[#21262d]',
    bgHeader: 'bg-[#161b22]',
    text: 'text-[#c9d1d9]',
    textSecondary: 'text-[#8b949e]',
    textMuted: 'text-[#484f58]',
    border: 'border-[#30363d]',
    borderHover: 'hover:border-[#484f58]',
    cardBg: 'bg-[#161b22]',
    codeBg: 'bg-[#0d1117]',
    consoleBg: 'bg-[#0d1117]',
    consoleText: 'text-[#c9d1d9]',
    buttonBg: 'bg-[#21262d]',
    buttonHover: 'hover:bg-[#30363d]',
    buttonActiveBg: 'bg-[#30363d]',
    accentBg: 'bg-[#388bfd]/20',
    accentText: 'text-[#58a6ff]',
    accentBorder: 'border-[#58a6ff]',
    successBg: 'bg-[#238636]/20',
    successText: 'text-[#3fb950]',
    warningBg: 'bg-[#9e6a03]/20',
    warningText: 'text-[#d29922]',
    dangerBg: 'bg-[#da3633]/20',
    dangerText: 'text-[#f85149]',
    editorTheme: 'vs-dark',
    shadow: 'shadow-lg shadow-black/30',
    tabActive: 'border-b-2 border-[#58a6ff] text-[#58a6ff]',
    tabInactive: 'text-[#8b949e] hover:text-[#c9d1d9]',
    inputBg: 'bg-[#0d1117]',
    inputBorder: 'border-[#30363d]',
    inputFocus: 'focus:ring-[#58a6ff] focus:border-[#58a6ff]',
    outputBg: 'bg-[#161b22]',
    outputText: 'text-[#c9d1d9]',
    outputBorder: 'border-[#30363d]',
  },
};

export default themes;
